import requests
check='5'
# Proxy sources
http_urls = [
"https://raw.githubusercontent.com/saisuiu/Lionkings-Http-Proxys-Proxies/main/free.txt",
"http://globalproxies.blogspot.com/",
"http://www.cybersyndrome.net/plz.html",
"http://www.cybersyndrome.net/plr5.html",
"http://biskutliat.blogspot.com/",
"http://freeproxylist-daily.blogspot.com/2013/05/usa-proxy-list-2013-05-15-0111-am-gmt8.html",
"http://freeproxylist-daily.blogspot.com/2013/05/usa-proxy-list-2013-05-13-812-gmt7.html",
"http://www.cybersyndrome.net/pla5.html",
"http://vipprox.blogspot.com/2013_06_01_archive.html",
"http://vipprox.blogspot.com/2013/05/us-proxy-servers-74_24.html",
"http://vipprox.blogspot.com/p/blog-page_7.html",
"http://vipprox.blogspot.com/2013/05/us-proxy-servers-199_20.html",
"http://vipprox.blogspot.com/2013_02_01_archive.html",
"http://alexa.lr2b.com/proxylist.txt",
"http://vipprox.blogspot.com/2013_03_01_archive.html",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196260",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196258",
"http://sock5us.blogspot.com/2013/06/01-07-13-free-proxy-server-list.html#comment-form",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196251",
"http://free-ssh.blogspot.com/feeds/posts/default",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196259",
"http://sockproxy.blogspot.com/2013/04/11-04-13-socks-45.html",
"http://proxyfirenet.blogspot.com/",
"https://www.javatpoint.com/proxy-server-list",
"https://openproxy.space/list/http",
"http://proxydb.net/",
"http://olaf4snow.com/public/proxy.txt",
"http://westdollar.narod.ru/proxy.htm",
"https://openproxy.space/list/socks4",
"https://openproxy.space/list/socks5",
"http://tomoney.narod.ru/help/proxi.htm",
"http://sergei-m.narod.ru/proxy.htm",
"http://rammstein.narod.ru/proxy.html",
"http://greenrain.bos.ru/R_Stuff/Proxy.htm",
"http://inav.chat.ru/ftp/proxy.txt",
"http://johnstudio0.tripod.com/index1.htm",
"http://atomintersoft.com/transparent_proxy_list",
"http://atomintersoft.com/anonymous_proxy_list",
"http://atomintersoft.com/high_anonymity_elite_proxy_list",
"http://atomintersoft.com/products/alive-proxy/proxy-list/3128",
"http://atomintersoft.com/products/alive-proxy/proxy-list/com",
"http://atomintersoft.com/products/alive-proxy/proxy-list/high-anonymity/",
"http://atomintersoft.com/products/alive-proxy/socks5-list",
"http://atomintersoft.com/proxy_list_domain_com",
"http://atomintersoft.com/proxy_list_domain_edu",
"http://atomintersoft.com/proxy_list_domain_net",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",
"http://atomintersoft.com/proxy_list_domain_org",
"http://atomintersoft.com/proxy_list_port_3128",
"http://atomintersoft.com/proxy_list_port_80",
"http://atomintersoft.com/proxy_list_port_8000",
"http://atomintersoft.com/proxy_list_port_81",
"http://hack-hack.chat.ru/proxy/allproxy.txt",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
"http://hack-hack.chat.ru/proxy/anon.txt",
"http://hack-hack.chat.ru/proxy/p1.txt",
"http://hack-hack.chat.ru/proxy/p2.txt",
"http://hack-hack.chat.ru/proxy/p3.txt",
"http://hack-hack.chat.ru/proxy/p4.txt",
"https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://free-proxy-list.net/",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt",
"https://www.us-proxy.org/",
"https://free-proxy-list.com/",
"https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt",
"https://api.proxyscrape.com/?request=getproxies&proxytype=http&timeout=10000&country=all&ssl=all&anonymity=all",
"https://api.proxyscrape.com/?request=getproxies&proxytype=socks4&timeout=10000&country=all",
"https://api.proxyscrape.com/?request=getproxies&proxytype=socks5&timeout=10000&country=all",
"https://spys.one/",
"https://api.proxyscrape.com/?request=getproxies&proxytype=https&timeout=10000&country=all&ssl=all&anonymity=all",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=10000&country=all",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/proxy.txt",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt",
"https://api.openproxylist.xyz/http.txt",
"https://api.openproxylist.xyz/socks4.txt",
"https://api.openproxylist.xyz/socks5.txt",
"https://www.proxy-list.download/api/v1/get?type=http",
"https://www.proxy-list.download/api/v1/get?type=https",
"https://www.proxy-list.download/api/v1/get?type=socks4",
"https://www.proxy-list.download/api/v1/get?type=socks5",
"https://www.proxyscan.io/download?type=http",
"https://www.proxyscan.io/download?type=https",
"https://www.proxyscan.io/download?type=socks4",
"https://www.proxyscan.io/download?type=socks5",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks4",
"https://api.proxyscrape.com/?request=displayproxies&proxytype=socks4",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt",
"https://www.proxy-list.download/api/v1/get?type=socks4",
"https://www.proxyscan.io/download?type=socks4",
"https://api.openproxylist.xyz/socks4.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
"https://www.my-proxy.com/free-socks-4-proxy.html",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt",
"http://proxysearcher.sourceforge.net/Proxy/List.php?type=socks",
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt",
"http://www.socks24.org/feeds/posts/default",
"https://www.freeproxychecker.com/result/socks4_proxies.txt",
"http://worm.rip/socks4.txt",
"https://www.freeproxychecker.com/result/socks4_proxies.txt",
"http://k2ysarchive.xyz/proxy/socks4.txt",
"https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5",
"https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5",
"https://www.proxy-list.download/api/v1/get?type=socks5",
"https://www.proxyscan.io/download?type=socks5",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt",
"https://www.my-proxy.com/free-socks-5-proxy.html",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt",
"https://github.com/roosterkid/openproxylist/blob/main/SOCKS5_RAW.txt",
"https://api.openproxylist.xyz/socks5.txt",
"""https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt""",
"""https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5", "timeout": 5},""",
"http://www.socks24.org/feeds/posts/default",
"https://www.freeproxychecker.com/result/socks5_proxies.txt",
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt",
"http://worm.rip/socks5.txt",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
"http://k2ysarchive.xyz/proxy/socks5.txt",
"https://api.proxyscrape.com/?request=displayproxies&proxytype=http",
"https://www.proxy-list.download/api/v1/get?type=http",
"https://www.proxyscan.io/download?type=http",
"http://spys.me/proxy.txt",
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://www.my-proxy.com/free-proxy-list.html",
"https://raw.githubusercontent.com/shiftytr/proxy-list/master/proxy.txt",
"https://www.my-proxy.com/free-anonymous-proxy.html",
"https://www.my-proxy.com/free-transparent-proxy.html",
"https://www.my-proxy.com/free-proxy-list-2.html",
"https://www.my-proxy.com/free-proxy-list-3.html",
"https://www.my-proxy.com/free-proxy-list-4.html",
"https://proxy50-50.blogspot.com/",
"https://www.my-proxy.com/free-proxy-list-5.html",
"http://alexa.lr2b.com/proxylist.txt",
"http://rootjazz.com/proxies/proxies.txt",
"https://www.freeproxychecker.com/result/http_proxies.txt",
"https://www.my-proxy.com/free-socks-4-proxy.html",
"http://www.proxyserverlist24.top/feeds/posts/default",
"https://www.my-proxy.com/free-proxy-list-6.html",
"https://www.my-proxy.com/free-proxy-list-7.html",
"https://www.my-proxy.com/free-proxy-list-8.html",
"http://proxysearcher.sourceforge.net/Proxy%20List.php?type=http",
"https://www.my-proxy.com/free-proxy-list-9.html",
"https://www.my-proxy.com/free-proxy-list-10.html",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
"https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt",
"https://raw.githubusercontent.com/UserR3X/proxy-list/main/online/http.txt",
"https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
"https://raw.githubusercontent.com/opsxcq/proxy-list/master/list.txt",
"https://proxy-spider.com/api/proxies.example.txt",
"https://multiproxy.org/txt_all/proxy.txt",
"http://rootjazz.com/proxies/proxies.txt",
"https://raw.githubusercontent.com/clarketm/proxy",
"http://k2ysarchive.xyz/proxy/http.txt",
"https://proxyspace.pro/http.txt",
"https://proxyspace.pro/https.txt",
"https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all",
"https://www.proxy-list.download/api/v1/get?type=http&anon=elite&country=US",
"https://raw.githubusercontent.com/shiftytr/proxy-list/master/proxy.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt",
"https://hidemy.name/en/proxy-list/",
"https://raw.githubusercontent.com/proxylist-to/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks5.txt",
"https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks4.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-https.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://www.proxy-list.download/api/v1/get?type=http",
"https://www.proxy-list.download/api/v1/get?type=https",
"https://www.proxyscan.io/download?type=http",
"https://www.proxyscan.io/download?type=https",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all",
"https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/HyperBeats/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt",
"https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/proxy.txt",
"http://hack-hack.chat.ru/proxy/allproxy.txt",
"http://hack-hack.chat.ru/proxy/p1.txt",
"http://hack-hack.chat.ru/proxy/p2.txt",
"http://hack-hack.chat.ru/proxy/p3.txt",
"http://inav.chat.ru/ftp/proxy.txt",
"https://cyber-hub.pw/statics/proxy.txt",
"https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/all.txt",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
"https://www.proxy-list.download/api/v1/get?type=socks5",
"https://www.proxyscan.io/download?type=socks5",
"https://api.openproxylist.xyz/socks5.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks5.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt",
"https://raw.githubusercontent.com/manuGMG/proxy-365/main/SOCKS5.txt",
"https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks5.txt",
"https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks5.txtA",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt",
"     https://eu1.proxysite.com/process.php?d=",
"     https://eu2.proxysite.com/process.php?d=",
"     https://eu3.proxysite.com/process.php?d=",
"     https://eu4.proxysite.com/process.php?d=",
"     https://eu5.proxysite.com/process.php?d=",
"     https://eu6.proxysite.com/process.php?d=",
"     https://eu7.proxysite.com/process.php?d=",
"     https://eu8.proxysite.com/process.php?d=",
"     https://eu9.proxysite.com/process.php?d=",
"     https://eu10.proxysite.com/process.php?d=",
"     https://us1.proxysite.com/process.php?d=",
"     https://us2.proxysite.com/process.php?d=",
"     https://us3.proxysite.com/process.php?d=",
"     https://us4.proxysite.com/process.php?d=",
"     https://us5.proxysite.com/process.php?d=",
"     https://us6.proxysite.com/process.php?d=",
"     https://us7.proxysite.com/process.php?d=",
"     https://us8.proxysite.com/process.php?d=",
"     https://us9.proxysite.com/process.php?d=",
"     https://us10.proxysite.com/process.php?d=",
"     https://us11.proxysite.com/process.php?d=",
"     https://us12.proxysite.com/process.php?d=",
"     https://us13.proxysite.com/process.php?d=",
"     https://us14.proxysite.com/process.php?d=",
"     https://us15.proxysite.com/process.php?d=",
"     https://divine.graphics/proxy.php?",
"     https://www.localizaip.com.br/localizar-ip.php?ip=",
"    http://www.meuenderecoip.com/localizar-ip.php?ip=",
"     https://website-down.com/",
"    http://proxy.clgt.net/proxy.php/",
"     https://www.pinterest.com/pin/create/button/?url=",
"     https://www.reddit.com/login/?dest=",
"     https://www.reddit.com/submit?url=",
"     https://www.filterbypass.me/s.php?k=",
"     https://www.filterbypass.me/?url=",
"     https://quantrimang.com/url?q=",
"     https://learnsql.xyz/chuyen-huong/?url=",
"     https://user.gtarcade.com/site/login?rurl=",
"    http://e9geolgzk6.com/iuqasfg3?dbqfdh=34&refer=",
"     https://iplookup.flagfox.net/?host=",
"     https://foradoar.org/",
"     https://duckduckgo.com/",
"     https://www.google.com/",
"     https://www.youtube.com",
"    http://www.google.com/?q=",
"     https://www.responsinator.com/?url=",
"     https://king.host/wiki/?url=",
"     https://website.grader.com/results/",
"     https://sitecheck.sucuri.net/results/",
"     https://www.ssllabs.com/ssltest/analyze.html?d=",
"     https://transparencyreport.google.com/safe-browsing/search?url=",
"     https://www.webpagetest.org/?url=",
"     https://www.hostinger.com.br/tutoriais/?url=",
"     https://www.sslshopper.com/ssl-checker.html#hostname=",
"     https://safeweb.norton.com/report/show?url=",
"    http://www.usatoday.com/search/results?q=",
"    http://engadget.search.aol.com/search?q=",
"    http://validator.w3.org/check?uri=",
"    http://www.facebook.com/sharer/sharer.php?u=",
"    http://downforeveryoneorjustme.com/",
"    http://network-tools.com/default.asp?prog=ping&host=",
"    http://network-tools.com/default.asp?prog=trace&host=",
"    http://network-tools.com/default.asp?prog=network&host=",
"     https://domainr.com/?q=",
"     https://down.is/",
"    http://whois.domaintools.com/",
"     https://downforeveryoneorjustme.com/",
"     https://www.webhostinghero.com/#",
"     https://www.whoishostingthis.com/#search=",
"     https://ping.eu/port-chk/?url=",
"     https://www.host-tracker.com/?url=",
"    http://hostchecker.net/?url=",
"     https://hostingchecker.com/?url=",
"     https://www.virustotal.com/vi/?url=",
"    http://tainhachay.mobi/?url=",
"    http://trangtainhac.info/?url=",
"    http://globalproxies.blogspot.com/",
"http://www.samair.ru/proxy/ip-address-15.htm",
"http://www.cybersyndrome.net/plz.html",
"http://aliveproxies.com/",
"http://www.cybersyndrome.net/plr5.html",
"http://biskutliat.blogspot.com/",
"http://freeproxylist-daily.blogspot.com/2013/05/usa-proxy-list-2013-05-15-0111-am-gmt8.html",
"http://proxylists.net/http_highanon.txt",
"http://freeproxylist-daily.blogspot.com/2013/05/usa-proxy-list-2013-05-13-812-gmt7.html",
"http://www.cybersyndrome.net/pla5.html",
"http://vipprox.blogspot.com/2013_06_01_archive.html",
"http://vipprox.blogspot.com/2013/05/us-proxy-servers-74_24.html",
"http://vipprox.blogspot.com/p/blog-page_7.html",
"http://vipprox.blogspot.com/2013/05/us-proxy-servers-199_20.html",
"http://freeforall.ucoz.com/forum/16-13723-1",
"http://vipprox.blogspot.com/2013_02_01_archive.html",
"http://alexa.lr2b.com/proxylist.txt",
"http://7proxy.blogspot.com/",
"http://vipprox.blogspot.com/2013_03_01_archive.html",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196260",
"http://www.samair.ru/proxy/ip-address-09.htm",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196258",
"http://sock5us.blogspot.com/2013/06/01-07-13-free-proxy-server-list.html#comment-form",
"http://www.samair.ru/proxy/proxy-13.htm",
"http://www.proxyfire.net/forum/forumdisplay.php?s=07a031a5ab87d88a9e048f534a0498a8&f=17",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196251",
"http://free-ssh.blogspot.com/feeds/posts/default",
"http://www.samair.ru/proxy/proxy-18.htm",
"http://www.samair.ru/proxy/proxy-15.htm",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196259",
"http://www.sockfree.net/2013/04/142013-sock-free-update-1128.html",
"http://www.samair.ru/proxy/proxy-20.htm",
"http://www.sockfree.net/2013/04/142013-sock-free-update-1139.html",
"http://sockproxy.blogspot.com/",
"http://free-ssh.blogspot.com/",
"http://sock5us.blogspot.com/",
"http://www.samair.ru/proxy/proxy-12.htm",
"http://sockproxy.blogspot.com/2013/04/11-04-13-socks-45.html",
"http://www.samair.ru/proxy/time-09.htm",
"http://proxyfirenet.blogspot.com/",
"http://globalproxies.blogspot.com/",
"http://www.cybersyndrome.net/plz.html",
"http://www.cybersyndrome.net/plr5.html",
"http://biskutliat.blogspot.com/",
"http://freeproxylist-daily.blogspot.com/2013/05/usa-proxy-list-2013-05-15-0111-am-gmt8.html",
"http://freeproxylist-daily.blogspot.com/2013/05/usa-proxy-list-2013-05-13-812-gmt7.html",
"http://www.cybersyndrome.net/pla5.html",
"http://vipprox.blogspot.com/2013_06_01_archive.html",
"http://vipprox.blogspot.com/2013/05/us-proxy-servers-74_24.html",
"http://vipprox.blogspot.com/p/blog-page_7.html",
"http://vipprox.blogspot.com/2013/05/us-proxy-servers-199_20.html",
"http://vipprox.blogspot.com/2013_02_01_archive.html",
"http://alexa.lr2b.com/proxylist.txt",
"http://vipprox.blogspot.com/2013_03_01_archive.html",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196260",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196258",
"http://sock5us.blogspot.com/2013/06/01-07-13-free-proxy-server-list.html#comment-form",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196251",
"http://free-ssh.blogspot.com/feeds/posts/default",
"http://browse.feedreader.com/c/Proxy_Server_List-1/449196259",
"http://sockproxy.blogspot.com/2013/04/11-04-13-socks-45.html",
"http://proxyfirenet.blogspot.com/",
"https://www.javatpoint.com/proxy-server-list",
"https://openproxy.space/list/http",
"http://proxydb.net/",
"http://olaf4snow.com/public/proxy.txt",
"http://westdollar.narod.ru/proxy.htm",
"https://openproxy.space/list/socks4",
"https://openproxy.space/list/socks5",
"http://tomoney.narod.ru/help/proxi.htm",
"http://sergei-m.narod.ru/proxy.htm",
"http://rammstein.narod.ru/proxy.html",
"http://greenrain.bos.ru/R_Stuff/Proxy.htm",
"http://inav.chat.ru/ftp/proxy.txt",
"http://johnstudio0.tripod.com/index1.htm",
"http://atomintersoft.com/transparent_proxy_list",
"http://atomintersoft.com/anonymous_proxy_list",
"http://atomintersoft.com/high_anonymity_elite_proxy_list",
"http://atomintersoft.com/products/alive-proxy/proxy-list/3128",
"http://atomintersoft.com/products/alive-proxy/proxy-list/com",
"http://atomintersoft.com/products/alive-proxy/proxy-list/high-anonymity/",
"http://atomintersoft.com/products/alive-proxy/socks5-list",
"http://atomintersoft.com/proxy_list_domain_com",
"http://atomintersoft.com/proxy_list_domain_edu",
"http://atomintersoft.com/proxy_list_domain_net",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",
"http://atomintersoft.com/proxy_list_domain_org",
"http://atomintersoft.com/proxy_list_port_3128",
"http://atomintersoft.com/proxy_list_port_80",
"http://atomintersoft.com/proxy_list_port_8000",
"http://atomintersoft.com/proxy_list_port_81",
"http://hack-hack.chat.ru/proxy/allproxy.txt",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
"http://hack-hack.chat.ru/proxy/anon.txt",
"http://hack-hack.chat.ru/proxy/p1.txt",
"http://hack-hack.chat.ru/proxy/p2.txt",
"http://hack-hack.chat.ru/proxy/p3.txt",
"http://hack-hack.chat.ru/proxy/p4.txt",
"https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://free-proxy-list.net/",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt",
"https://www.us-proxy.org/",
"https://free-proxy-list.com/",
"https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt",
"https://api.proxyscrape.com/?request=getproxies&proxytype=http&timeout=10000&country=all&ssl=all&anonymity=all",
"https://api.proxyscrape.com/?request=getproxies&proxytype=socks4&timeout=10000&country=all",
"https://api.proxyscrape.com/?request=getproxies&proxytype=socks5&timeout=10000&country=all",
"https://spys.one/",
"https://api.proxyscrape.com/?request=getproxies&proxytype=https&timeout=10000&country=all&ssl=all&anonymity=all",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=10000&country=all",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/proxy.txt",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all",
"https://free-proxy-list.net/",
"http://www.freeproxylists.net/",
"https://github.com/clarketm/proxy-list/blob/master/proxy-list-raw.txt",
"https://spys.one/en/",
"https://www.proxynova.com/proxy-server-list",
"https://www.sslproxies.org/",
"https://openproxy.space/list",
"https://www.proxyscan.io/",
"http://proxydb.net/",
"https://advanced.name/freeproxy?ddexp4attempt=1",
"http://nntime.com/",
"https://www.duplichecker.com/free-proxy-list.php",
"https://hidemy.name/en/proxy-list/",
"https://scrapingant.com/free-proxies/",
"https://www.proxynova.com/proxy-server-list/",
"https://hidester.com/proxylist/",
"https://www.us-proxy.org/",
"http://www.freeproxy.ru/en/free_proxy/get.htm",
"https://www.proxyrack.com/free-proxy-list/",
"https://www.coderduck.com/free-proxy-list",
"https://proxyservers.pro/",
"https://www.proxy-list.download/HTTP",
"https://list.proxylistplus.com/Fresh-HTTP-Proxy-List-1",
"https://www.hide-my-ip.com/proxylist.shtml",
"https://proxyranker.com/",
"https://proxyhttp.net/",
"https://sockslist.net/",
"http://proxy-list.org/german/index.php",
"https://www.proxylist4all.com/",
"https://proxypremium.top/download-proxy-list",
"https://www.netzwelt.de/proxy/index.html",
"http://www.proxyliste.com/",
"https://www.proxy-listen.de/Proxy/Proxyliste.html",
"https://smallseotools.com/es/free-proxy-list/",
"https://list.proxylistplus.com/Fresh-HTTP-Proxy-List-1",
"https://free-proxy-list.com/",
"https://www.proxyranker.com/",
"https://www.eleaks.to",
"https://sockslist.net/proxy/server-socks-hide-ip-address/",
"https://premiumproxy.net/distorting-proxy-list",
"https://proxied.network/",
"https://coolproxies.com/proxy-list.php",
"https://www.freeproxy.world/",
"https://proxies.gg/",
"https://www.proxyrotator.com/free-proxy-list/",
"http://proxy11.com/free-proxy",
"http://aliveproxy.com/high-anonymity-proxy-list/",
"https://multiproxy.org/all_proxy.htm",
"http://www.multiproxy.org/anon_proxy.htm",
"http://www.publicproxyservers.com/page1.html",
"http://www.anonymitychecker.com/page1.html",
"http://www.digitalcybersoft.com/ProxyList/fresh-proxy-list.shtml",
"http://www.proxz.com/",
"http://tools.rosinstrument.com/proxy/",
"http://www.samair.ru/proxy/",
"https://premiumproxy.net/",
"https://hidemy.name/en/proxy-list/",
"http://www.idcloak.com/proxylist/proxy-list.html",
"https://www.proxynova.com/proxy-server-list/",
"https://premproxy.com/list/",
"https://hidester.com/proxylist/",
"https://openproxy.space/list",
"http://proxydb.net/",
"https://geonode.com/free-proxy-list",
"https://www.proxy-list.download/HTTP",
"https://spys.one/en/free-proxy-list/",
"https://secure.echolink.org/proxylist.jsp",
"http://083.us/socks-proxy-list.htm",
"http://0distance.nease.net/proxy.htm",
"http://0linh.blogspot.com/2009/11/free-proxy-20112009.html",
"http://1000freeanonymousproxy.blogspot.com/2011/08/12-august-2011-fast-anonymous-proxy.html",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt",
"https://api.proxyscrape.com/?request=displayproxies&timeout=10000",
"https://cyber-hub.pw/statics/proxy.txt",
"http://proxyscrape.com/",
"http://sslproxies24.blogspot.in/feeds/posts/default",
"http://rootjazz.com/proxies/proxies.txt",
"http://www.live-socks.net/feeds/posts/default",
"http://www.httptunnel.ge/ProxyListForFree.aspx",
"https://hidemy.name/en/proxy-list/",
"https://free-proxy-list.net/",
"https://www.proxynova.com/",
"http://www.proxylists.net/",
"http://www.freeproxylists.net/",
"http://Gatherproxy.com",
"http://free-proxy.cz/en/",
"http://spys.one/en/",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all",
"https://openproxy.space/list/http",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"http://pubproxy.com/api/proxy",
"https://www.juproxy.com/free_api",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/hyperbeats/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-https.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/https_raw.txt",
"https://raw.githubusercontent.com/shiftytr/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/thespeedx/proxy-list/master/http.txt",
"https://www.proxy-list.download/api/v1/get?type=http",
"https://www.proxy-list.download/api/v1/get?type=https",
"https://www.proxyscan.io/download?type=http",
"https://www.proxyscan.io/download?type=https",
"https://openproxy.space/list/socks5",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
"https://api.openproxylist.xyz/socks5.txt",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
"https://raw.githubusercontent.com/hyperbeats/proxy-list/main/socks5.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt",
"https://raw.githubusercontent.com/manugmg/proxy-365/main/socks5.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks5.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/socks5_raw.txt",
"https://raw.githubusercontent.com/saschazesiger/free-proxies/master/proxies/socks5.txt",
"https://raw.githubusercontent.com/shiftytr/proxy-list/master/socks5.txt",
"https://raw.githubusercontent.com/thespeedx/proxy-list/master/socks5.txt",
"https://www.proxy-list.download/api/v1/get?type=socks5",
"https://www.proxyscan.io/download?type=socks5",
"https://openproxy.space/list/socks4",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt",
"https://www.socks-proxy.net/",
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=10000&country=all",
"https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt",
"https://www.proxy-list.download/api/v1/get?type=socks4",
"https://www.proxyscan.io/download?type=socks4",
"https://api.openproxylist.xyz/socks4.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks4.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt",
"https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txt",
"https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies/socks4.txt",
"https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks4.txt",
"https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks4.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/proxy.txt",
"https://github.com/ShiftyTR/Proxy-List/raw/master/socks4.txt",
"https://github.com/ShiftyTR/Proxy-List/raw/master/socks5.txt",
"https://api.getproxylist.com/proxy",
"https://api.getproxylist.com/proxy?lastTested=600",
"https://api.getproxylist.com/proxy?port[]=80&port[]=8080",
"https://api.getproxylist.com/proxy?anonymity[]=high%20anonymity&anonymity[]=transparent",
"https://api.getproxylist.com/proxy?protocol[]=socks4&protocol[]=socks5",
"https://api.getproxylist.com/proxy?allowsRefererHeader=1",
"https://api.getproxylist.com/proxy?allowsUserAgentHeader=1",
"https://api.getproxylist.com/proxy?allowsCustomHeaders=1",
"https://api.getproxylist.com/proxy?allowsCookies=1",
"https://api.getproxylist.com/proxy?allowsPost=1",
"https://api.getproxylist.com/proxy?allowsHttps=1",
"https://api.getproxylist.com/proxy?country[]=CA&country[]=US",
"https://api.getproxylist.com/proxy?notCountry[]=CA&notCountry[]=US",
"https://api.getproxylist.com/proxy?ip[]=31.202.117.137&ip[]=211.153.17.151",
"https://api.getproxylist.com/proxy?all=1",
"https://github.com/TheSpeedX/PROXY-List/raw/master/http.txt",
"https://github.com/TheSpeedX/PROXY-List/raw/master/socks4.txt",
"https://github.com/TheSpeedX/PROXY-List/raw/master/socks5.txt",
"https://github.com/jetkai/proxy-list/raw/main/online-proxies/txt/proxies-http.txt",
"https://github.com/jetkai/proxy-list/raw/main/online-proxies/txt/proxies-https.txt",
"https://github.com/jetkai/proxy-list/raw/main/online-proxies/txt/proxies-socks4.txt",
"https://github.com/jetkai/proxy-list/raw/main/online-proxies/txt/proxies-socks5.txt",
"https://github.com/jetkai/proxy-list/raw/main/online-proxies/txt/proxies.txt",
"https://github.com/monosans/proxy-list/raw/main/proxies/http.txt",
"https://github.com/monosans/proxy-list/raw/main/proxies/socks4.txt",
"https://github.com/monosans/proxy-list/raw/main/proxies/socks5.txt",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/tg/mtproto.json",
"https://raw.githubusercontent.com/hookzof/socks5_list/master/tg/socks.json",
"https://github.com/mmpx12/proxy-list/raw/master/http.txt",
"https://github.com/mmpx12/proxy-list/raw/master/https.txt",
"https://github.com/mmpx12/proxy-list/raw/master/proxies.txt",
"https://github.com/mmpx12/proxy-list/raw/master/socks4.txt",
"https://github.com/mmpx12/proxy-list/raw/master/socks5.txt",
"https://github.com/UptimerBot/proxy-list/raw/main/proxies/http.txt",
"https://github.com/UptimerBot/proxy-list/raw/main/proxies/socks4.txt",
"https://github.com/UptimerBot/proxy-list/raw/main/proxies/socks5.txt",
"https://github.com/zevtyardt/proxy-list/raw/main/all.txt",
"https://github.com/roosterkid/openproxylist/raw/main/HTTPS_RAW.txt",
"https://github.com/roosterkid/openproxylist/raw/main/SOCKS4_RAW.txt",
"https://github.com/roosterkid/openproxylist/raw/main/SOCKS5_RAW.txt",
"https://github.com/saschazesiger/Free-Proxies/raw/master/proxies/all.txt",
"https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/raw.txt",
"https://github.com/mertguvencli/http-proxy-list/raw/main/proxy-list/data.txt",
"https://raw.githubusercontent.com/saisuiu/Lionkings-Http-Proxys-Proxies/main/cnfree.txt",
"https://raw.githubusercontent.com/prxchk/proxy-list/main/http.txt", 
"https://raw.githubusercontent.com/prxchk/proxy-list/main/all.txt",
"https://raw.githubusercontent.com/andigwandi/free-proxy/main/proxy_list.txt",
 "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=500&country=all",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-https.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
    "https://www.proxy-list.download/api/v1/get?type=http",
    "https://www.proxyscan.io/download?type=http",
    "https://api.openproxylist.xyz/http.txt",
    "https://github.com/mmpx12/proxy-list/raw/master/http.txt",
"https://github.com/UptimerBot/proxy-list/raw/main/proxies/http.txt",
"https://github.com/monosans/proxy-list/raw/main/proxies/http.txt",
"https://github.com/jetkai/proxy-list/raw/main/online-proxies/txt/proxies-http.txt",
"https://github.com/TheSpeedX/PROXY-List/raw/master/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/thespeedx/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/shiftytr/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/hyperbeats/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/HyperBeats/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/proxylist-to/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://proxyspace.pro/http.txt",
"http://k2ysarchive.xyz/proxy/http.txt",
"https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://raw.githubusercontent.com/Bardiafa/Proxy-Leecher/main/proxies.txt",
"https://raw.githubusercontent.com/Bardiafa/Proxy-Leecher/main/good.txt",
"https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt",
"https://raw.githubusercontent.com/mertguvencli/http-proxy-list/main/proxy-list/data.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/http.txt",
"https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://raw.githubusercontent.com/yoannchb-pro/https-proxies/main/proxies.txt",
"https://raw.githubusercontent.com/UptimerBot/proxy-list/master/proxies/http.txt",
'https://raw.githubusercontent.com/UptimerBot/proxy-list/master/proxies/http.txt',
'https://raw.githubusercontent.com/UptimerBot/proxy-list/master/proxies/http.txt',
'https://raw.githubusercontent.com/andigwandi/free-proxy/main/proxy_list.txt',
'https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/http/http.txt',
'https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt',
'https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt',
'https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt',
'https://raw.githubusercontent.com/caliphdev/Proxy-List/master/http.txt',
'https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt',
'https://raw.githubusercontent.com/fahimscirex/proxybd/master/anonymous-proxylist/http.txt',
'https://raw.githubusercontent.com/ToShukKr/rProxyList/main/proxy-list.txt',
'https://raw.githubusercontent.com/prxchk/proxy-list/main/http.txt',
]

socks4_urls = [
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt",
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=10000&country=all",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-socks4.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
    "https://www.proxy-list.download/api/v1/get?type=socks4",
    "https://www.proxyscan.io/download?type=socks4",
    "https://api.openproxylist.xyz/socks4.txt"
]

socks5_urls = [
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt",
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-socks5.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt",
    "https://github.com/jetkai/proxy-list/blob/main/archive/txt/proxies-socks5.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt",
    "https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",
    "https://www.proxy-list.download/api/v1/get?type=socks5",
    "https://www.proxyscan.io/download?type=socks5",
    "https://api.openproxylist.xyz/socks5.txt"
]

all_urls = [
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-https.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
    "https://www.proxy-list.download/api/v1/get?type=http",
    "https://www.proxy-list.download/api/v1/get?type=https",
    "https://www.proxyscan.io/download?type=http",
    "https://www.proxyscan.io/download?type=https",
    "https://api.openproxylist.xyz/http.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt",
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=10000&country=all",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-socks4.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
    "https://www.proxy-list.download/api/v1/get?type=socks4",
    "https://www.proxyscan.io/download?type=socks4",
    "https://api.openproxylist.xyz/socks4.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt",
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-socks5.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt",
    "https://github.com/jetkai/proxy-list/blob/main/archive/txt/proxies-socks5.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt",
    "https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",
    "https://www.proxy-list.download/api/v1/get?type=socks5",
    "https://www.proxyscan.io/download?type=socks5",
    "https://api.openproxylist.xyz/socks5.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies.txt",
    "https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
    "https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/proxy.txt",
    "http://hack-hack.chat.ru/proxy/allproxy.txt",
    "http://hack-hack.chat.ru/proxy/p1.txt",
    "http://hack-hack.chat.ru/proxy/p2.txt",
    "http://hack-hack.chat.ru/proxy/p3.txt",
    "http://hack-hack.chat.ru/proxy/p4.txt",
    "http://olaf4snow.com/public/proxy.txt",
    "http://alexa.lr2b.com/proxylist.txt",
    "http://inav.chat.ru/ftp/proxy.txt",
        "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=500&country=all",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-https.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
    "https://www.proxy-list.download/api/v1/get?type=http",
    "https://www.proxyscan.io/download?type=http",
    "https://api.openproxylist.xyz/http.txt",
    "https://github.com/mmpx12/proxy-list/raw/master/http.txt",
"https://github.com/UptimerBot/proxy-list/raw/main/proxies/http.txt",
"https://github.com/monosans/proxy-list/raw/main/proxies/http.txt",
"https://github.com/jetkai/proxy-list/raw/main/online-proxies/txt/proxies-http.txt",
"https://github.com/TheSpeedX/PROXY-List/raw/master/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/thespeedx/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/shiftytr/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/hyperbeats/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/HyperBeats/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies-http.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/proxylist-to/proxy-list/main/http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://proxyspace.pro/http.txt",
"http://k2ysarchive.xyz/proxy/http.txt",
"https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://api.openproxylist.xyz/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://raw.githubusercontent.com/Bardiafa/Proxy-Leecher/main/proxies.txt",
"https://raw.githubusercontent.com/Bardiafa/Proxy-Leecher/main/good.txt",
"https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt",
"https://raw.githubusercontent.com/mertguvencli/http-proxy-list/main/proxy-list/data.txt",
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/http.txt",
"https://raw.githubusercontent.com/yemixzy/proxy-list/main/proxies/http.txt",
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
"https://raw.githubusercontent.com/yoannchb-pro/https-proxies/main/proxies.txt",
"https://raw.githubusercontent.com/UptimerBot/proxy-list/master/proxies/http.txt",
'https://raw.githubusercontent.com/UptimerBot/proxy-list/master/proxies/http.txt',
'https://raw.githubusercontent.com/UptimerBot/proxy-list/master/proxies/http.txt',
'https://raw.githubusercontent.com/andigwandi/free-proxy/main/proxy_list.txt',
'https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/http/http.txt',
'https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt',
'https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt',
'https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt',
'https://raw.githubusercontent.com/caliphdev/Proxy-List/master/http.txt',
'https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt',
'https://raw.githubusercontent.com/fahimscirex/proxybd/master/anonymous-proxylist/http.txt',
'https://raw.githubusercontent.com/ToShukKr/rProxyList/main/proxy-list.txt',
'https://raw.githubusercontent.com/prxchk/proxy-list/main/http.txt',

]

unique_arr = list(set(http_urls))
live_socks = []
import threading
import socks
import ssl
import time
import sys
import requests
def hehe(i):
    try:
        a=requests.get(url=i.strip(),timeout=1).text.strip()
        if (a.find('o')==-1) and (a.find('a')==-1):
            live_socks.append(requests.get(url=i.strip(),timeout=3).text.strip()+'\n')
            print(i.strip())
    except:
        hehehe=123512
import threading
thread_list=[]
for i in unique_arr:
    thread = threading.Thread(target=hehe, args=(i, ))
    thread.start()
    thread_list.append(thread)
    sys.stdout.flush()
for thread in thread_list:
    thread.join()
    sys.stdout.flush()
file = open('proxy.txt', "w")
for socks_address in live_socks:
    try:
        file.write(socks_address + "\n")
    except:
        hehehe=543543
file.close()
with open('proxy.txt', 'r') as file:
    lines = file.readlines()

# Tạo danh sách duy nhất từ nội dung đọc được
unique_lines = list(set(lines))

# Mở tệp 'proxy.txt' ở chế độ ghi để ghi lại danh sách duy nhất
with open('proxy.txt', 'w') as file:
    for line in unique_lines:
        file.write(line)

# Đóng tệp
file.close()

